### PR TITLE
Feature/newshub

### PR DESCRIPTION
**Pull request by ksytwu100**
I know that there are merge conflicts and am creating this PR to review.

### CODE REVIEW

**Review by ksytwu100 — COMMENTED** [review]
Removed duplicates from rountes.js. All other changes only affect the Login/Signup styles and handlebars.

**Review by CrispinDD1 — COMMENTED** [review]
🎣

**Review by CrispinDD1 — COMMENTED** [review]
🎣

**Review by CrispinDD1 — APPROVED** [review]
🎣

**Pull request merged**
